version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rosca_postgres
    restart: always
    environment:
      POSTGRES_USER: rosca_user
      POSTGRES_PASSWORD: rosca_pass
      POSTGRES_DB: rosca_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rosca_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rosca.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data:
