"""Initial migration: users table

Revision ID: 225f4555adde
Revises: c4d129eb7492
Create Date: 2026-03-11 01:05:20.379217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '225f4555adde'
down_revision: Union[str, None] = 'c4d129eb7492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First add currency as nullable to avoid NOT NULL violation
    op.add_column('groups', sa.Column('currency', sa.String(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE groups SET currency = 'USD' WHERE currency IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('groups', 'currency',
               existing_type=sa.String(),
               nullable=False)
    
    # Handle other columns that might be NULL (from your migration output)
    op.execute("UPDATE groups SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column('groups', 'updated_at',
               existing_type=sa.DateTime(),
               nullable=False)
    
    op.execute("UPDATE groups SET total_cycles_completed = 0 WHERE total_cycles_completed IS NULL")
    op.alter_column('groups', 'total_cycles_completed',
               existing_type=sa.Integer(),
               nullable=False)
    
    op.execute("UPDATE groups SET total_collected = 0 WHERE total_collected IS NULL")
    op.alter_column('groups', 'total_collected',
               existing_type=sa.Float(),
               nullable=False)
    
    op.execute("UPDATE groups SET total_paid_out = 0 WHERE total_paid_out IS NULL")
    op.alter_column('groups', 'total_paid_out',
               existing_type=sa.Float(),
               nullable=False)
    
    op.execute("UPDATE groups SET is_active = true WHERE is_active IS NULL")
    op.alter_column('groups', 'is_active',
               existing_type=sa.Boolean(),
               nullable=False)
    # ### end Alembic commands ###