"""update userrole to super_admin and user only

Revision ID: 461236b837fc
Revises: 4aac0e322caf
Create Date: 2026-03-24 17:25:11.375256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461236b837fc'
down_revision: Union[str, None] = '4aac0e322caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('payout_order', sa.Integer(), nullable=True),
    sa.Column('guarantor_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['guarantor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'contributions', 'memberships', ['membership_id'], ['id'])
    op.create_foreign_key(None, 'groups', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'payout_schedules', 'memberships', ['member_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'payout_schedules', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.drop_table('memberships')
    # ### end Alembic commands ###
