"""recreate users table with correct enum

Revision ID: 4aac0e322caf
Revises: 77c03343f7ac
Create Date: 2026-03-24 16:53:34.762412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aac0e322caf'
down_revision: Union[str, None] = '77c03343f7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=2), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'GROUP_ADMIN', 'GROUP_MEMBER', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_foreign_key(None, 'groups', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'memberships', 'users', ['guarantor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
