"""Add currency field to contributions

Revision ID: 60db2ce229b9
Revises: cddbf3a82d1c
Create Date: 2026-03-09 01:43:36.490555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60db2ce229b9'
down_revision: Union[str, None] = 'cddbf3a82d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('contributions', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('contributions', sa.Column('base_currency_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('groups', sa.Column('date_format', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('language', sa.String(length=2), nullable=True))
    op.add_column('groups', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('preferred_currency', sa.String(length=3), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_currency')
    op.drop_column('users', 'preferred_language')
    op.drop_column('groups', 'timezone')
    op.drop_column('groups', 'language')
    op.drop_column('groups', 'date_format')
    op.drop_column('contributions', 'base_currency_amount')
    op.drop_column('contributions', 'exchange_rate')
    op.drop_column('contributions', 'currency')
    # ### end Alembic commands ###
