"""update userrole enum to user and super_admin

Revision ID: 77c03343f7ac
Revises: c3e58a942a13
Create Date: 2026-03-24 07:57:36.054792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77c03343f7ac'
down_revision: Union[str, None] = 'c3e58a942a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'GROUP_ADMIN', 'GROUP_MEMBER', name='userrole'),
               nullable=True,
               existing_server_default=sa.text("'GROUP_MEMBER'::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'GROUP_ADMIN', 'GROUP_MEMBER', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'GROUP_MEMBER'::userrole"))
    # ### end Alembic commands ###
