"""Initial migration: users table

Revision ID: c3090d6d65f5
Revises: 60db2ce229b9
Create Date: 2026-03-09 05:25:39.073343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3090d6d65f5'
down_revision: Union[str, None] = '60db2ce229b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_group_per_user', 'groups', ['name', 'created_by'])
    op.create_unique_constraint(None, 'groups', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_constraint('unique_group_per_user', 'groups', type_='unique')
    # ### end Alembic commands ###
