"""Add cycle tracking fields

Revision ID: c4d129eb7492
Revises: db84308c1d4d
Create Date: 2026-03-10 10:59:56.014709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'c4d129eb7492'
down_revision: Union[str, None] = 'db84308c1d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First add cycle_number as nullable
    op.add_column('contributions', sa.Column('cycle_number', sa.Integer(), nullable=True))
    
    # Add group columns as nullable first
    op.add_column('groups', sa.Column('contribution_period', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('rosca_type', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('total_cycles_completed', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('next_payout_date', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('total_collected', sa.Float(), nullable=True))
    op.add_column('groups', sa.Column('total_paid_out', sa.Float(), nullable=True))
    op.add_column('groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows in groups table
    op.execute("UPDATE groups SET contribution_period = 'weekly' WHERE contribution_period IS NULL")
    op.execute("UPDATE groups SET rosca_type = 'random' WHERE rosca_type IS NULL")
    op.execute("UPDATE groups SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE groups SET total_cycles_completed = 0 WHERE total_cycles_completed IS NULL")
    op.execute("UPDATE groups SET total_collected = 0 WHERE total_collected IS NULL")
    op.execute("UPDATE groups SET total_paid_out = 0 WHERE total_paid_out IS NULL")
    op.execute("UPDATE groups SET is_active = true WHERE is_active IS NULL")
    
    # Set default values for existing rows in contributions table
    op.execute("UPDATE contributions SET cycle_number = 1 WHERE cycle_number IS NULL")
    
    # Now make columns NOT NULL
    op.alter_column('contributions', 'cycle_number', nullable=False)
    op.alter_column('groups', 'contribution_period', nullable=False)
    op.alter_column('groups', 'rosca_type', nullable=False)
    op.alter_column('groups', 'updated_at', nullable=False, server_default=sa.text('NOW()'))
    op.alter_column('groups', 'total_cycles_completed', nullable=False, server_default='0')
    op.alter_column('groups', 'total_collected', nullable=False, server_default='0')
    op.alter_column('groups', 'total_paid_out', nullable=False, server_default='0')
    op.alter_column('groups', 'is_active', nullable=False, server_default='true')
    
    # Continue with the existing alter operations
    op.alter_column('groups', 'contribution_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    
    # Drop constraints and columns
    op.drop_constraint('groups_name_key', 'groups', type_='unique')
    op.drop_constraint('unique_group_per_user', 'groups', type_='unique')
    op.drop_column('groups', 'status')
    op.drop_column('groups', 'country_code')
    op.drop_column('groups', 'timezone')
    op.drop_column('groups', 'date_format')
    op.drop_column('groups', 'currency')
    op.drop_column('groups', 'language')
    op.drop_column('groups', 'contribution_frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('contribution_frequency', postgresql.ENUM('daily', 'weekly', 'monthly', name='frequency'), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('date_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('status', postgresql.ENUM('active', 'completed', 'paused', name='group_status'), autoincrement=False, nullable=True))
    op.create_unique_constraint('unique_group_per_user', 'groups', ['name', 'created_by'])
    op.create_unique_constraint('groups_name_key', 'groups', ['name'])
    op.alter_column('groups', 'contribution_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('groups', 'is_active')
    op.drop_column('groups', 'total_paid_out')
    op.drop_column('groups', 'total_collected')
    op.drop_column('groups', 'next_payout_date')
    op.drop_column('groups', 'total_cycles_completed')
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'rosca_type')
    op.drop_column('groups', 'contribution_period')
    op.drop_column('contributions', 'cycle_number')
    # ### end Alembic commands ###