"""Add payout schedules table

Revision ID: db84308c1d4d
Revises: c3090d6d65f5
Create Date: 2026-03-10 09:50:30.897068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db84308c1d4d'
down_revision: Union[str, None] = 'c3090d6d65f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payout_schedules', sa.Column('contribution_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payout_schedules', 'contribution_ids')
    # ### end Alembic commands ###
