"""fix userrole enum handling

Revision ID: e7b52c1f3131
Revises: 461236b837fc
Create Date: 2026-03-24 18:46:29.579109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b52c1f3131'
down_revision: Union[str, None] = '461236b837fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('contributions', sa.Column('cycle_number', sa.Integer(), nullable=False))
    op.add_column('contributions', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('contributions', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.add_column('contributions', sa.Column('paid_date', sa.DateTime(), nullable=True))
    op.add_column('contributions', sa.Column('status', sa.Enum('pending', 'paid', 'late', name='payment_status'), nullable=True))
    op.add_column('contributions', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('contributions', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('contributions', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('contributions', sa.Column('base_currency_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('contributions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('contributions', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_constraint('contributions_membership_id_fkey', 'contributions', type_='foreignkey')
    op.create_foreign_key(None, 'contributions', 'memberships', ['membership_id'], ['id'])
    op.create_foreign_key(None, 'contributions', 'groups', ['group_id'], ['id'])
    op.drop_column('contributions', 'contributed_at')
    op.add_column('groups', sa.Column('contribution_amount', sa.Float(), nullable=False))
    op.add_column('groups', sa.Column('contribution_period', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('member_count', sa.Integer(), nullable=False))
    op.add_column('groups', sa.Column('rosca_type', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('current_cycle', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('total_cycles_completed', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('next_payout_date', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('total_collected', sa.Float(), nullable=True))
    op.add_column('groups', sa.Column('total_paid_out', sa.Float(), nullable=True))
    op.drop_constraint('memberships_user_id_group_id_key', 'memberships', type_='unique')
    op.drop_constraint('memberships_group_id_fkey', 'memberships', type_='foreignkey')
    op.drop_constraint('memberships_user_id_fkey', 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'memberships', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'payout_schedules', 'memberships', ['member_id'], ['id'])
    op.create_foreign_key(None, 'payout_schedules', 'groups', ['group_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'user', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'user'::userrole"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'user', name='userrole'),
               nullable=True,
               existing_server_default=sa.text("'user'::userrole"))
    op.drop_constraint(None, 'payout_schedules', type_='foreignkey')
    op.drop_constraint(None, 'payout_schedules', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key('memberships_user_id_fkey', 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('memberships_group_id_fkey', 'memberships', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('memberships_user_id_group_id_key', 'memberships', ['user_id', 'group_id'])
    op.drop_column('groups', 'total_paid_out')
    op.drop_column('groups', 'total_collected')
    op.drop_column('groups', 'next_payout_date')
    op.drop_column('groups', 'start_date')
    op.drop_column('groups', 'total_cycles_completed')
    op.drop_column('groups', 'current_cycle')
    op.drop_column('groups', 'currency')
    op.drop_column('groups', 'rosca_type')
    op.drop_column('groups', 'member_count')
    op.drop_column('groups', 'contribution_period')
    op.drop_column('groups', 'contribution_amount')
    op.add_column('contributions', sa.Column('contributed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.create_foreign_key('contributions_membership_id_fkey', 'contributions', 'memberships', ['membership_id'], ['id'], ondelete='CASCADE')
    op.alter_column('contributions', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('contributions', 'created_at')
    op.drop_column('contributions', 'base_currency_amount')
    op.drop_column('contributions', 'exchange_rate')
    op.drop_column('contributions', 'notes')
    op.drop_column('contributions', 'payment_method')
    op.drop_column('contributions', 'status')
    op.drop_column('contributions', 'paid_date')
    op.drop_column('contributions', 'due_date')
    op.drop_column('contributions', 'currency')
    op.drop_column('contributions', 'cycle_number')
    op.drop_column('contributions', 'group_id')
    # ### end Alembic commands ###
